### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by mani-barathi** [mani-barathi/Google-Photos-Clone#1]
There is a typo in `README` under **Technology Used** section. 
The word **Cloud** is misspelled as **Clourd**.

Anybody who is interested in contributing can fix this typo and make a PR.

**Comment by PushpakB3096** [comment]
Can I work on this?

**Comment by mani-barathi** [comment]
@PushpakB3096 sure. make changes and give a PR

**Comment by PushpakB3096** [comment]
@mani-barathi Done. Please review and merge if everything looks good.

**Comment by mani-barathi** [comment]
> @mani-barathi Done. Please review and merge if everything looks good.

Thank u
